apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
  labels:
        app: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1 
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.13
        ports:
        - name: http
          containerPort: 9200
        - name: transport
          containerPort: 9300
        env:
        - name: discovery.type
          value: "single-node"
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: esvolume
          
      volumes: 
      - name: esvolume
        emptyDir: {}
        

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch   
  type: LoadBalancer
  ports:
  - port: 9200
    protocol: TCP
    name: http
    targetPort: 9200
  - port: 9300
    protocol: TCP
    name: transport
    targetPort: 9300
    